os: linux
language: node_js
node_js:
  - '12'

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - docker ps -a

script:
  - npm run test

after_script:
  - docker-compose -f docker-compose.travis.yml down
