version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - ./src/config/docker.env
    ports:
      - '8000:8000'
    container_name: api_app
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    command: npm run dev

  mysql:
    image: mysql:5.7.31
    restart: always
    env_file:
      - ./src/config/dev.env
    ports:
      - '3306:3306'
    container_name: api_db
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    container_name: api_cache
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
